- name: Translate hieradata
  include_role:
    name: 'ansible-role-k8s-tripleo'
  vars:
    hieradata: '{{hiera_data}}'
    hieradata_file: '{{hiera_data_file}}'
    schema:
      cinder::api::bind_port: DEFAULT.bind_port
      cinder::notify::rabbitmq::rabbit_userid: oslo_messaging_rabbit.rabbit_userid
      cinder::notify::rabbitmq::rabbit_port: oslo_messaging_rabbit.rabbit_port
      cinder::notify::rabbitmq::rabbit_password: oslo_messaging_rabbit.rabbit_password
      cinder::notify::rabbitmq::rabbit_use_ssl: oslo_messaging_rabbit.rabbit_use_ssl
      cinder::notify::rabbitmq::rabbit_host: oslo_messaging_rabbit.rabbit_host
      cinder::rabbit_userid: cinder_rabbit_user
      cinder::rabbit_password: cinder_rabbit_password
      cinder::rabbit_port: cinder_rabbit_port
