- name: Generate config files
  config_template:
    src: rbd/ceph.conf.j2
    dest: /tmp/ceph.conf
    config_type: ini

- name: Read configs into memory
  slurp:
    src: "/tmp/ceph.conf"
  register: "ceph_conf"

- name: Create cinder-volume-ceph configmaps
  ignore_errors: yes
  k8s_v1_config_map:
    name: cinder-volume-ceph
    namespace: "{{ namespace }}"
    state: present
    debug: yes
    labels:
      service: cinder-volume-ceph
    data:
      config.json: |
        {
            "command": "/usr/bin/cinder-volume --config-file /usr/share/cinder/cinder-dist.conf --config-file /etc/cinder/cinder.conf",
            "config_files": [
                {
                    "source": "/var/lib/kolla/config_files/cinder.conf",
                    "dest": "/etc/cinder/cinder.conf",
                    "owner": "cinder",
                    "perm": "0600"
                },
                {
                    "source": "/var/lib/kolla/config_files/ceph.conf",
                    "dest": "/etc/ceph/ceph.conf",
                    "owner": "root",
                    "perm": "0644"
                }
            ],
            "permissions": [
                {
                    "path": "/var/lib/cinder",
                    "owner": "cinder:cinder",
                    "recurse": true
                },
                {
                    "path": "/var/log/kolla/cinder",
                    "owner": "cinder:cinder",
                    "recurse": true
                }
            ]
        }

      cinder.conf: |
        {{cinder_conf['content'] | b64decode}}


- set_fact:
    init_container:
      - name: updated-config
        image: tripleoupstream/centos-binary-kolla-toolbox
        imagePullPolicy: "IfNotPresent"
        command:
          - /bin/sh
          - -c
          - |
            cp -a /srv/configmap/..data/* /srv/pod-main-config/;
            cp -a /srv/ceph/..data/* /srv/pod-main-config/;
            CONF=/srv/pod-main-config/cinder.conf;
            crudini --set $CONF DEFAULT transport_url rabbit://guest:$RABBITMQ_PASSWORD@rabbitmq:5672/?ssl=0;
            crudini --set $CONF oslo_messaging_notifications transport_url rabbit://guest:$RABBITMQ_PASSWORD@rabbitmq:5672/?ssl=0;
            crudini --set $CONF database connection mysql+pymysql://root:$DB_ROOT_PASSWORD@mariadb:3306/cinder;
            crudini --set $CONF database password $CINDER_PASSWORD;
        env:
        - name: DB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cinder-secrets
              key: mariadb-root-password
        - name: CINDER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cinder-secrets
              key: cinder-password
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cinder-secrets
              key: rabbitmq-password

        volumeMounts:
         - name: template-config
           mountPath: /srv/configmap
         - name: final-config
           mountPath: /srv/pod-main-config
         - name: ceph-secrets
           mountPath: /srv/ceph

- name: Create Cinder Volume Deployment
  k8s_v1beta2_deployment:
    name: cinder-volume-ceph
    namespace: "{{ namespace }}"
    service_account_name: "{{ service_account }}"
    labels:
      app: cinder-volume-ceph
      service: cinder-volume-ceph
    replicas: 1
    spec_template_metadata_labels:
      app: cinder-volume-ceph
      service: cinder-volume-ceph
    init_containers:
      - name: updated-config
        image: tripleoupstream/centos-binary-kolla-toolbox
        imagePullPolicy: "IfNotPresent"
        command:
          - /bin/sh
          - -c
          - |
            cp -a /srv/configmap/..data/* /srv/pod-main-config/;
            cp -a /srv/ceph/..data/* /srv/pod-main-config/;
            CONF=/srv/pod-main-config/cinder.conf;
            crudini --set $CONF DEFAULT transport_url rabbit://guest:$RABBITMQ_PASSWORD@rabbitmq:5672/?ssl=0;
            crudini --set $CONF oslo_messaging_notifications transport_url rabbit://guest:$RABBITMQ_PASSWORD@rabbitmq:5672/?ssl=0;
            crudini --set $CONF database connection mysql+pymysql://root:$DB_ROOT_PASSWORD@mariadb:3306/cinder;
            crudini --set $CONF database password $CINDER_PASSWORD;
        env:
        - name: DB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cinder-secrets
              key: mariadb-root-password
        - name: CINDER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cinder-secrets
              key: cinder-password
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cinder-secrets
              key: rabbitmq-password

        volumeMounts:
         - name: template-config
           mountPath: /srv/configmap
         - name: final-config
           mountPath: /srv/pod-main-config
         - name: ceph-secrets
           mountPath: /srv/ceph

    containers:
    - name: cinder-volume
      image: tripleoupstream/centos-binary-cinder-volume:latest
      volumeMounts:
        - name: kolla-config
          mountPath: /var/lib/kolla/config_files/
        - name: ceph-client-cinder-keyring
          mountPath: /etc/ceph/ceph.client.cinder.keyring
      env:
        - name: TZ
         value: UTC
        - name: KOLLA_CONFIG_STRATEGY
          value: COPY_ALWAYS
        - name: KOLLA_KUBERNETES
          value: ""
        - name: DB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cinder-secrets
              key: mariadb-root-password
        - name: CINDER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cinder-secrets
              key: cinder-password
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cinder-secrets
              key: rabbitmq-password

      volumeMounts:
        - name: final-config
          mountPath: /var/lib/kolla/config_files

    volumes:
      - name: template-config
        configMap:
          name: cinder-volume-ceph
      - name: final-config
        emptyDir: {}
      - name: ceph-secrets
        secret:
          secretName: ceph-secrets

